### ISSUE TITLE
DAP Connect-Cloud

### ISSUE THREAD

**Issue by wormscoffer** [kevinblumenfeld/Posh365#1]
Hello

I use the Connect-Cloud as it's perfect for connecting to my client's tenancies for running PowerShell against.

Would love the following couple of functionalities and thought there's no harm in asking.

1) Command line switch to close and disconnect the session before starting another.
2) Option to use "-tenant DAP" as a switch option that would then get the tenancies for which I have DAP access and then bring them up as a list for me to chose one from.

I'd love to be able to write something myself but it would probably take me months.

**Comment by kevinblumenfeld** [comment]
@wormscoffer Thank you for your kind words.  Do you still need this feature?  Do you have the microsoft code that you typically use to connect with?  is it across msonline, exo, exo2, etc?

**Comment by wormscoffer** [comment]
Hello @kevinblumenfeld 

I don't think I do at the moment but thanks for asking.

**Comment by kevinblumenfeld** [comment]
closing per thread
