### ISSUE TITLE
Duplicate Get-ExchangeDistributionGroup

### ISSUE THREAD

**Issue by itpro-tips** [kevinblumenfeld/Posh365#12]
Get-EXOGroup.ps1 is the same script as Get-ExchangeDistributionGroup so can be removed for better understanding and code update.
The only difference is about the OU attribute. To me it is not a problem because this attribute also exists in Office 365.

**Comment by kevinblumenfeld** [comment]
Thank you... Yeah I may need to consolidate @itpro-tips

**Comment by kevinblumenfeld** [comment]
This is a terrific idea however now that the EXO cmdlets are being released let's keep the two separated so we can use v2 when released.  Btw @itpro-tips  I have corrected Get-365Info to use new EXOv2 cmdlets.  Also Connect-Cloud Contoso -EXO2 -MSOnline for example will connect EXO2 last as there seems to be an issue connecting other services after EXO2 connects.  Thank you for your feedback and support!
