### ISSUE TITLE
Connect-IPPSSession Not working

### ISSUE THREAD

**Issue by samrajcse** [kevinblumenfeld/Posh365#13]
I am trying to execute the below command and it throws below error in Powershell 5.x ( Windows latest version).

Other commands such as Get-365Info are working fine.

Is there any option to pass the access / refresh token and convert to Credential object and use that for authentication. I seen few people doing that in their application. How we can do that? We can generate the Token via Oauth 2 and copy the token here and work out.

**Stack trace:**

PS C:\WINDOWS\system32> Connect-IPPSSession
Connect-IPPSSession : The term 'Connect-IPPSSession' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Connect-IPPSSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-IPPSSession:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by kevinblumenfeld** [comment]
@samrajcse thanks for you message.  That is a private function (meaning it is only used by other functions).

`Connect-Cloud -tenant contoso -msonline -exchange -MFA` 
will for example use that command.  

I don't know of a way to use MFA and save credentials.  This saves credentials for example:
`Connect-Cloud -tenant contoso -msonline -exchange` 
but only for those with accounts not enabled for MFA.

**Comment by kevinblumenfeld** [comment]
I am closing this issue as Connect-Cloud or Connect-CloudMFA are the functions that you need.
@samrajcse
