### ISSUE TITLE
Additional Columns

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#16]
Column for LicenseSuite
Column for EnableArchive
Column for ConvertToShared

**Comment by kevinblumenfeld** [comment]
@Neckross  working on this now.  In your opinion should CompleteBatchDate and CompleteBatchTimePT be removed from Batches file?

**Comment by kevinblumenfeld** [comment]
@Neckross this is complete and in Beta.  Please try

https://raw.githubusercontent.com/kevinblumenfeld/Posh365Demo/master/Posh365Demo/BackLevel/BatchesBeta.ps1

**Comment by kevinblumenfeld** [comment]
this is complete along with the Update-MailboxMoveBatchesReport and supporting functions
will  leave in batches until tested and confirmed as working properly
