### ISSUE TITLE
Get-MailboxPermission to not Display Migrated user permission and Display the granted user's Batch

### ISSUE THREAD

**Issue by PraveenKumarE** [kevinblumenfeld/Posh365#19]
Get-MailboxPermission to not Display Migrated user permission and Display the granted user's Batch using the 2 files Batches.xlxs and Permissions.xlxs

**Comment by kevinblumenfeld** [comment]
@PraveenKumarE can you confirm that this is complete?

**Comment by kevinblumenfeld** [comment]
@PraveenKumarE This is complete.. Closing per call with Praveen
