### ISSUE TITLE
Anyway to pass in Creds to Connect-CloudMFA -ExchangeOnline

### ISSUE THREAD

**Issue by swiftsolves-msft** [kevinblumenfeld/Posh365#20]
Looking to grab encrypted password and pass in creds programmatically however doesn't appear their is a parameter for -credentials ? Possible to incorporate or another way to programmatically pass creds into the Connect-CloudMFA -ExchangeOnline ?

**Comment by kevinblumenfeld** [comment]
For non-mfa? Have you tried connect-cloud?

**Comment by kevinblumenfeld** [comment]
@swiftsolves-msft I have added Connect-CloudMFA -EXO2 that passes the username. This is a wrapper for the new Connect-ExchangeOnline.  I am not aware of a way without Basic Authentication to pass credential.  However the latest from the Exchange team uses a token and does not seem to require a password after long period of idle time. 

By now, have you found a way to pass credentials during MFA?

**Comment by kevinblumenfeld** [comment]
@swiftsolves-msft closing.. Please let me know if I am missing the point in your original issue. Thank you.
