### ISSUE TITLE
Exchange Online module V2 in conflict with Posh365

### ISSUE THREAD

**Issue by itpro-tips** [kevinblumenfeld/Posh365#21]
Hello,
Microsoft releases new Exchange v2 CMDlets :
[https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Admin-Improvements-Announced-at-Microsoft-Ignite-2019/ba-p/982121](https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Exchange-Admin-Improvements-Announced-at-Microsoft-Ignite-2019/ba-p/982121)

and they use *-EXO* command too...
For example *Get-EXOMailbox* in Posh365 also exist in the new Exchange Online Module :(

**Comment by kevinblumenfeld** [comment]
@itpro-tips wow okay I will need to adjust .. thank you

**Comment by kevinblumenfeld** [comment]
@itpro-tips I have released version 0.9.30 which renames Get-EXOMailbox to Get-EXOnlineMailbox.
