### ISSUE TITLE
Get-DiscoveryUNIFORMnamespace

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#34]
can you make it uniform the naming convention for Discovery?
ex. Get-DiscoveryO365, Get-DiscoveryOkta, Get-DiscoveryAzure, Get-DiscoveryOnPrem
Thanks

**Comment by kevinblumenfeld** [comment]
@Neckross 
Thoughts on Verb-Noun options?....

Get-365Discovery
Get-OktaDiscovery
Get-AzureDiscovery
Get-OnPremDiscovery

**Comment by Neckross** [comment]
I think it's easier if you keep it as get-discovery because it's easiest to find it.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kevinblumenfeld** [comment]
This is complete:
Get-DiscoveryOnPrem
Get-DiscoveryOffice365
Get-DiscoveryOkta
Get-DiscoveryAzure
