### ISSUE TITLE
RoomsPermissionsDelegates include in Permissions.xlsx script

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#43]
good to have the rooms permissions and delegates included on the Permissions.xlsx file that allows to review prior to migrate those rooms to Office 365

**Comment by kevinblumenfeld** [comment]
Need more information

Please run Get-EXOResourceMailbox | Export-PoshExcel .\ResMailboxex.xlsx and email to me.  There are emails sent to delegates. Other than that I am wondering if this wasn't a calendar visibility issue.

[Calendar Processing](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-calendarprocessing?view=exchange-ps)

**-AutomateProcessing**

The AutomateProcessing parameter enables or disables calendar processing on the mailbox. Valid values are:

**None**: Calendar processing is disabled on the mailbox. Both the resource booking attendant and the Calendar Attendant are disabled on the mailbox.

**AutoUpdate**: Only the Calendar Attendant processes meeting requests and responses. Meeting requests are tentative in the calendar until they're approved by a delegate. Meeting organizers receive only decisions from delegates.

**AutoAccept**: Both the Calendar Attendant and resource booking attendant are enabled on the mailbox. This means that the Calendar Attendant updates the calendar, and then the resource booking assistant accepts the meeting based upon the policies. Eligible meeting organizers receive the decision directly without human intervention (free = accept; busy = decline).

**Comment by kevinblumenfeld** [comment]
by default a Resource Delegate is assign SendOnBehalf permissions over the Resource Mailbox

`Get-Mailbox Test4000@contoso.com | Set-CalendarProcessing -AllBookInPolicy:$false -AllRequestInPolicy:$false -AutomateProcessing Autoaccept -ResourceDelegates 'test3000@contoso.com'`

**Comment by Neckross** [comment]
I think this was a one-off case, so we can close the request.
