### ISSUE TITLE
Add Get-DiscoveryIntune function for Intune tenant discovery

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#51]
There's LOTS of improvement around this... there are a few modules already out there:

https://github.com/jseerden/IntuneBackupAndRestore
https://github.com/microsoft/Intune-PowerShell-SDK
https://github.com/microsoftgraph/powershell-intune-samples

**Comment by Neckross** [comment]
There's a module out there called "IntuneBackupAndRestore (https://github.com/jseerden/IntuneBackupAndRestore)" that helps to transition from tenant to tenant but can be useful as a Discovery, but is not a true Discovery... we should have Get-DiscoveryIntune set of functions dedicated to this goal... I'm gonna try to help with this one!

**Comment by kevinblumenfeld** [comment]
Get-DiscoveryIntune has been added
