### ISSUE TITLE
Update Connect-Exchange function from external (-Authentication Basic)

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#52]
function Connect-EMS_External {
 
  param (
    [Parameter(Mandatory = $False, ValueFromPipeline = $true)]
    $ConnectionUri = "https://hybrid..com/PowerShell"
  )
  $UserCredential = Get-Credential -UserName "juans.@.com" -Message "Enter DomainAdmin creds"
  $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $ConnectionUri -Credential $UserCredential -Authentication Basic
  Import-PSSession $Session
}
Connect-EMS_External

**Comment by kevinblumenfeld** [comment]
`Connect-Exchange -Basic` is okay?

**Comment by Neckross** [comment]
hmm maybe -Internal and by default should use -External

**Comment by kevinblumenfeld** [comment]
This is complete
