### ISSUE TITLE
To update line number in RemoveOPPLicense.ps1 

### ISSUE THREAD

**Issue by PraveenKumarE** [kevinblumenfeld/Posh365#54]
Line number 12 says                 $i += 6
it should be                              $i += 7

**Comment by kevinblumenfeld** [comment]
can you test this and show please?

**Comment by PraveenKumarE** [comment]
Testing, I believe it changes from subscription to subsription and we need to modify it accoringly. 

In mine if i want a particular subscription I need to use a 5 for other i need to use 6


PRODUCT ID: 00202-12345-12345-12345
SKU ID: 149dbce7-1234-1234-8364-a5338abc4580
LICENSE NAME: Office 16, Office16O365ProPlusR_Subscription1 edition
LICENSE DESCRIPTION: Office 16, TIMEBASED_SUB channel
LICENSE STATUS:  ---LICENSED---
ERROR CODE: 0x4004FC04 (for information purposes only as the status is licensed)
ERROR DESCRIPTION: The Software Licensing Service reported that the application is running within the timebased validity period.
REMAINING GRACE: 45 days  (65765 minute(s) before expiring)
Last 5 characters of installed product key: 12345
---------------------------------------
PRODUCT ID: 00213-12345-12345-12345
SKU ID: 2f72340c-1234-1234-1234-a5338abc4580
LICENSE NAME: Office 16, Office16ProjectProO365R_Subscription edition
LICENSE DESCRIPTION: Office 16, TIMEBASED_SUB channel
LICENSE STATUS:  ---NOTIFICATIONS---
ERROR CODE: 0xC004E022
ERROR DESCRIPTION: The Software Licensing Service reported that the secure store id value in license does not match with the current value.
Last 5 characters of installed product key: ABCDE
---------------------------------------



not sure if Office16O365ProPlusR_Subscription1  is always 6. In one environment i have seen it as 7

**Comment by kevinblumenfeld** [comment]
I am going to close this but I added a comment to the CBH
