### ISSUE TITLE
GUID instead of UserPrincipanName > Update functions

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365#60]
Please update functions for MailboxMove to use the ExchangeGuid instead of UserPrincipalName.

Sometimes we have remediations in the middle of the migration and we need to change UPN/SMTP/Alias, etc... in AD
However, that must reflect also in Batches.xlsx, but since we forget to update the sheet due to the number of remediations, then the New-MailboxMove fails because it still looking at the old incorrect value.

Thank you.

**Comment by kevinblumenfeld** [comment]
this is complete ExchangeGUID
